#!/usr/bin/env python3
"""Lock the canonical payload hash vector.

Run once, commit the output, and never edit it by hand:

    cd apps/api && python ../../scripts/lock_canonical_vector.py

Why this exists: the canonical serialisation is the thing that makes a
confirmation mean "I agreed to *these exact* details". If the routine changes,
every stored confirmation silently stops matching. Committing the exact bytes and
digest turns that from a silent data problem into a failing test.

Regenerating is a deliberate act. If ``test_locked_vector_matches`` fails and you
did not intend to change the serialisation, fix the code -- do not re-run this.
If you *did* intend to change it, bump ``CANONICAL_SCHEMA_VERSION`` first so old
and new hashes cannot be confused, then regenerate.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
API_ROOT = REPO_ROOT / "apps" / "api"
sys.path.insert(0, str(API_ROOT))

from app.domain.canonical import (  # noqa: E402
    CANONICAL_SCHEMA_VERSION,
    canonical_json,
    payload_hash,
)
from tests.test_canonical import REFERENCE, VECTOR_PATH  # noqa: E402


def main() -> int:
    VECTOR_PATH.parent.mkdir(parents=True, exist_ok=True)
    vector = {
        "_readme": (
            "Generated by scripts/lock_canonical_vector.py. Do not edit by hand. "
            "See that script's docstring before regenerating."
        ),
        "schema_version": CANONICAL_SCHEMA_VERSION,
        "canonical_json": canonical_json(REFERENCE),
        "sha256": payload_hash(REFERENCE),
    }
    VECTOR_PATH.write_text(
        json.dumps(vector, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"Wrote {VECTOR_PATH}")
    print(f"  schema_version: {vector['schema_version']}")
    print(f"  sha256:         {vector['sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
