"""Fixed disclosure and honesty copy, in one place.

These strings are requirements, not content. 02_EVIDENCE_AND_CLAIMS_LEDGER.md
fixes what this prototype may claim, and the persistent disclosure is the load-
bearing part of that: a reviewer must be able to tell at a glance that nothing here
touches a government system and no real data is involved.

They live in the API rather than the frontend so there is exactly one authoritative
copy. The SPA fetches them from ``/api/v1/meta`` and renders them verbatim, which
means ``tests/test_copy_lint.py`` can assert the wording once and cover every
screen at the same time.

Rules for editing this file:

*   The three disclosure fragments are verbatim requirements. Rewording them is a
    specification change, not a copy tweak.
*   Nothing here may name a government body as a participant, imply endorsement, or
    describe any output as official, valid, or legally effective.
*   No ``.gov.in`` or ``.nic.in`` string, no logo reference, no seal.
"""

from __future__ import annotations

#: The persistent banner. Present on every screen (05_UX_UI_INTERACTION_SPEC.md
#: section 3), which is why it is one string rather than three components.
DISCLOSURE_EN = (
    "Independent hackathon prototype · Government integrations are simulated · "
    "Uses fictional data"
)
DISCLOSURE_HI = (
    "स्वतंत्र हैकाथॉन प्रोटोटाइप · सरकारी इंटीग्रेशन सिम्युलेटेड हैं · काल्पनिक डेटा का उपयोग"
)

#: Shown in the "what this is" panel and in the source drawer.
ABOUT_EN = (
    "This is an independent hackathon prototype. It does not connect to any "
    "government system, it does not file anything, and nothing it produces has "
    "legal effect. Every registry response and every acknowledgement you see is "
    "simulated and uses fictional data."
)
ABOUT_HI = (
    "यह एक स्वतंत्र हैकाथॉन प्रोटोटाइप है। यह किसी सरकारी प्रणाली से नहीं जुड़ता, कुछ भी "
    "दाखिल नहीं करता, और इसका कोई भी परिणाम कानूनी रूप से प्रभावी नहीं है। यहाँ दिखने "
    "वाली प्रत्येक रजिस्ट्री प्रतिक्रिया और प्रत्येक पावती सिम्युलेटेड है और काल्पनिक डेटा "
    "का उपयोग करती है।"
)

#: Shown wherever the app asks for input, so the boundary is stated at the point
#: of risk rather than only in a footer.
NO_REAL_DATA_EN = (
    "Do not enter real Aadhaar, PAN, OTP, password, payment or any other personal "
    "details. This prototype neither needs nor accepts them."
)
NO_REAL_DATA_HI = (
    "कृपया वास्तविक आधार, पैन, ओटीपी, पासवर्ड, भुगतान या कोई अन्य व्यक्तिगत विवरण दर्ज "
    "न करें। इस प्रोटोटाइप को इनकी आवश्यकता नहीं है और यह इन्हें स्वीकार नहीं करता।"
)

#: The scope statement for the route selector. Names the excluded route so a user
#: is told the process exists elsewhere rather than being silently blocked.
SCOPE_EN = (
    "This prototype covers one journey: handing a registered vehicle to an "
    "authorised dealer under the current Form 29C mechanism. Selling to a private "
    "buyer is a different process and is out of scope here."
)
SCOPE_HI = (
    "यह प्रोटोटाइप एक ही प्रक्रिया कवर करता है: वर्तमान फॉर्म 29C व्यवस्था के अंतर्गत "
    "पंजीकृत वाहन को अधिकृत डीलर को सौंपना। निजी खरीदार को बिक्री एक अलग प्रक्रिया है "
    "और यहाँ शामिल नहीं है।"
)

#: What the two confirmations are, and are not. Rendered next to the confirm
#: button, because that is the moment a user is most likely to over-read it.
CONFIRMATION_MEANING_EN = (
    "Confirming records that you agree these details are correct. It is not an "
    "electronic signature and it does not submit anything by itself."
)
CONFIRMATION_MEANING_HI = (
    "पुष्टि करने से यह दर्ज होता है कि आप इन विवरणों से सहमत हैं। यह इलेक्ट्रॉनिक "
    "हस्ताक्षर नहीं है और अपने आप कुछ दाखिल नहीं करता।"
)

#: Attached to the acknowledgement screen. The one place a user might mistake the
#: prototype's output for a real record, so it says otherwise on the same screen.
ACKNOWLEDGEMENT_CAVEAT_EN = (
    "This acknowledgement number was generated by a simulated adapter inside this "
    "prototype. It is fictional, it exists only in this demo, and it is not proof "
    "of anything outside it."
)
ACKNOWLEDGEMENT_CAVEAT_HI = (
    "यह पावती संख्या इस प्रोटोटाइप के अंदर एक सिम्युलेटेड एडाप्टर द्वारा बनाई गई है। यह "
    "काल्पनिक है, केवल इस डेमो में मौजूद है, और इसके बाहर किसी बात का प्रमाण नहीं है।"
)

#: The legal anchor, stated as a description of the mechanism the prototype
#: models. Deliberately does not claim the prototype satisfies it.
POLICY_ANCHOR_EN = (
    "The checklist in this prototype mirrors the intimation-of-delivery mechanism "
    "introduced by G.S.R. 901(E) (Rules 55A-55F, Forms 29B-29F), which has been in "
    "force since 1 April 2023."
)
POLICY_ANCHOR_HI = (
    "इस प्रोटोटाइप की चेकलिस्ट जी.एस.आर. 901(E) (नियम 55A-55F, फॉर्म 29B-29F) द्वारा "
    "शुरू की गई सुपुर्दगी-सूचना व्यवस्था को दर्शाती है, जो 1 अप्रैल 2023 से लागू है।"
)


def meta_payload(*, build_label: str, policy_version: str, poll_interval_seconds: float) -> dict[str, object]:
    """The bundle the SPA fetches once at startup.

    Returned from the API so that a build with a stale frontend bundle still shows
    the current disclosure wording.
    """
    return {
        "simulation": True,
        "build_label": build_label,
        "policy_version": policy_version,
        "poll_interval_seconds": poll_interval_seconds,
        "disclosure": {"en": DISCLOSURE_EN, "hi": DISCLOSURE_HI},
        "about": {"en": ABOUT_EN, "hi": ABOUT_HI},
        "no_real_data": {"en": NO_REAL_DATA_EN, "hi": NO_REAL_DATA_HI},
        "scope": {"en": SCOPE_EN, "hi": SCOPE_HI},
        "confirmation_meaning": {
            "en": CONFIRMATION_MEANING_EN,
            "hi": CONFIRMATION_MEANING_HI,
        },
        "acknowledgement_caveat": {
            "en": ACKNOWLEDGEMENT_CAVEAT_EN,
            "hi": ACKNOWLEDGEMENT_CAVEAT_HI,
        },
        "policy_anchor": {"en": POLICY_ANCHOR_EN, "hi": POLICY_ANCHOR_HI},
    }


__all__ = [
    "ABOUT_EN",
    "ABOUT_HI",
    "ACKNOWLEDGEMENT_CAVEAT_EN",
    "ACKNOWLEDGEMENT_CAVEAT_HI",
    "CONFIRMATION_MEANING_EN",
    "CONFIRMATION_MEANING_HI",
    "DISCLOSURE_EN",
    "DISCLOSURE_HI",
    "NO_REAL_DATA_EN",
    "NO_REAL_DATA_HI",
    "POLICY_ANCHOR_EN",
    "POLICY_ANCHOR_HI",
    "SCOPE_EN",
    "SCOPE_HI",
    "meta_payload",
]
